# Generated by Django 4.1.3 on 2022-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fec_inscripcion', models.DateField(max_length=30)),
                ('hora', models.TimeField(max_length=30)),
                ('Institucion', models.CharField(max_length=30)),
                ('rutP', models.CharField(max_length=30)),
                ('nombrep', models.CharField(max_length=30)),
                ('Num_telefono', models.IntegerField(max_length=30)),
                ('Est_reserva', models.CharField(choices=[('reserva', 'RESERVA'), ('completo', 'COMPLETo'), ('anuladar', 'ANULADAR'), ('no asisten', 'NO ASISTEN')], max_length=30)),
                ('Observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
